"use client"
import { useEffect } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import AOS from 'aos';
import 'aos/dist/aos.css';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Aditya Pratap",
//   // description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: false,
    });
  }, []);
  return (
    <html lang="en">
      <body >
        <Sidebar/>
        {children}
        </body>
    </html>
  );
}
